version: "3.8"

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql-retalho
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: steve3571
      MYSQL_DATABASE: retalho_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - retalho-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psteve3571"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: retalho
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-retalho:3306/retalho_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: steve3571
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_TYPE_PREFERRED_UUID_JDBC_TYPE: CHAR
      SPRING_RABBITMQ_HOST: localhost
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: steve3571
    depends_on:
      mysql:
        condition: service_healthy # Mantenha se adicionou o healthcheck
    networks:
      - retalho-net

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq-retalho
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456

volumes:
  mysql-data:
  rabbitmq_data:

networks:
  retalho-net:
    driver: bridge